th3cyb3rhub/TheCyberHUB

- index.html
A common noun  in singular number always requires an article before it but it is better to leave this in plural form
--Thecyberhub is the best platform for hacker to learn cybersecurity for free--
should be 
--Thecyberhub is the best platform for hackers to learn cybersecurity for free--
> fix: Correction in the description on meta tag

- src/components/Prep/Jobs/JobsElements.jsx
Fixed Bug for a wider screen. This is my first open-source contribution, request you to please review it and let me know if I am missing something 😄 
**Before**
**After**
> fixed css issue

- src/components/Events/EventsElement.jsx
- src/components/Events/OnGoingEvents/OnGoingEventsElements.jsx
- src/components/Events/UpComingEvents/UpComingEventsElements.jsx
Closes #222 
Alignment issue on the events page for upcoming, today, and past events.
##Screenshot
> fix: Alignment issue on the events page

- src/components/Footer/FooterElements.jsx
- src/components/MixComponents/Buttons/ButtonElements.jsx
Example: Closes #232
Add scale and optional increase to font size on hover to make button elements (or any element actually)  scale without causing other elements to move
---
> fix: allow buttons to transition without affecting other elements

- src/features/blogs/blogService.js
- src/features/blogs/blogSlice.js
closes #334 
**OLD ISSUE:** without this change the server would read the comment as undefined.
**FIX:** ajax needs to send "comment" inside a JSON body.
In ViewBlog.jsx line 77:
dispatch(addComment({ blogId: searchedBlog._id, addCommentData }));
addComment was being called by sending blogID and addCommentData inside one object not seperated
There is an infinite loading issue after submitting a comment even though the comment has been added to the database and can be seen after reloading the page.
--- …
> Fix: add Comments on blogs not working

- package-lock.json
- package.json
- src/components/Dashboard/Dashboard.jsx
- src/components/Dashboard/DashboardElements.jsx
- src/components/Dashboard/Notetaker/AddNote.jsx
- src/components/Dashboard/Notetaker/Note.jsx
- src/components/Dashboard/Notetaker/NoteApp.css
- src/components/Dashboard/Notetaker/NoteApp.jsx
- src/components/Dashboard/Notetaker/NoteList.jsx
- src/components/Dashboard/OldDashbaord/DashboardItems.jsx
- src/components/Dashboard/Profile/ProfileElements.jsx
- src/components/Explore/Users/UsersElements.jsx
Closes #442 
You can now add and remove a note in the dashboard.
The styling needs some work and maybe the functionality of not having to start with a note already open.
---
> Created note taking functionality in dashboard

- src/NotFound.jsx
- src/components/Blogs/BlogCard/BlogCards.jsx
- src/components/CaptureTheFlag/CTFCards/CtfChallenges.jsx
- src/components/Explore/Explore.jsx
- src/components/Explore/FeedsExplore.jsx
- src/components/Explore/Users/Users.jsx
Closes #459 
https://github.com/thecyberworld/TheCyberHUB/assets/76536506/e1bee736-3a2f-4187-9a2f-6774b7db4914
I checked the loading property in the state of different modals from the redux, while it is true the spinner will appear. I didn't create new state , so I didn't manage state instead I used already existing one
* I think so, tell me if there is a need to fix something
---
Join the Thecyberworld GitHub Organisation by raising an [issue](https://github.com/thecyberworld/Support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+O …
> Feature/Handle Loading And Empty Data Message

- src/App.jsx
- src/components/ChatBot/ActionProvider.jsx
- src/components/ChatBot/ChatbotElements.jsx
- src/components/ChatBot/MessageParser.jsx
- src/components/ChatBot/TCHBot.jsx
- src/components/ChatBot/Widgets/Assists/AssistElements.jsx
- src/components/ChatBot/Widgets/Assists/AssistLinks.jsx
- src/components/ChatBot/Widgets/Assists/AssistLinksData.jsx
- src/components/ChatBot/Widgets/Assists/AssistOptions.jsx
- src/components/ChatBot/Widgets/BotComponents/TCHBotAvatar.jsx
- src/components/ChatBot/config.jsx
> feat: Chatbot

- src/components/Dashboard/Notetaker/NoteApp.jsx
- src/components/Dashboard/Notetaker/NoteDescription.jsx
- src/components/Dashboard/Notetaker/NoteItem.jsx
- src/components/Dashboard/Notetaker/NoteList.jsx
- src/features/notes/notesService.js
- src/features/notes/notesSlice.js
Related to Issue #474 
https://github.com/thecyberworld/TheCyberHUB/assets/76536506/d7d7b3b5-65ef-4386-88f0-ad972e2b1495
---
> [Feat] Connect Notes to Backend

- src/components/Common/InputEditor/InputEditor.jsx
- src/components/Common/InputEditor/InputEditorElements.jsx
- src/components/Common/MarkdownEditor/CheckBoxClickable.jsx
- src/components/Common/MarkdownEditor/MarkdownEditor.css
- src/components/Common/MarkdownEditor/MarkdownEditor.jsx
- src/components/Common/MarkdownEditor/MarkdownEditorElements.jsx
- src/components/Common/MarkdownEditor/useEditorImage.jsx
- src/components/Common/MarkdownEditor/useImageUploadEvents.jsx
- src/components/Dashboard/Notetaker/NoteApp.jsx
- src/components/Dashboard/Notetaker/NoteDescription.jsx
- src/components/Dashboard/Notetaker/NoteElements.jsx
- src/components/Dashboard/Notetaker/NoteItem.jsx
- src/features/notes/notesSlice.js
- src/pages/ForgotPassword.jsx
- src/pages/Login.jsx
- src/pages/Register.jsx
- src/pages/ResetPassword.jsx
Some tweaks in functionality and styles:
1. change "undescribedNote" to "(Empty)"
2. remove id from "untitledNote" to "untitledNote #number"
3. remove all the address of the image and leave only the name of image
4. change the title editor , dont need to preview what we input
5. make description and description preview in edit mode scrollable
6. handle text overflow when needed
https://github.com/thecyberworld/TheCyberHUB/assets/76536506/287ea908-685c-4f9c-896e-3ad31bd96d0a
need to add to list of things to do :)
--- …
> feat: notes | Func of Paste, Drop Image In editor

- src/components/Dashboard/Notetaker/Category/CategorySidebar.jsx
- src/components/Dashboard/Notetaker/NoteApp.css
- src/components/Dashboard/Notetaker/NoteApp.jsx
- src/components/Dashboard/Notetaker/NoteDescription.jsx
- src/components/Dashboard/Notetaker/NoteSidebar.jsx
- src/features/notes/category/categoryService.js
- src/features/notes/category/categorySlice.js
https://github.com/thecyberworld/TheCyberHUB/assets/76536506/7c74b6ac-7efb-457a-b436-a52e7bda8ed7
---
> feat: notes | category connect to backend

- src/components/CheatSheets/CheatSheet.jsx
- src/components/CheatSheets/CheatSheetElements.jsx
- src/components/Dashboard/Profile/ProfileElements.jsx
Changed the mobile view from 600px to 800px and added toggle features for hamburger menu and made Hack Book responsive for mobile and tablet
Closes #578 
- [] I have updated the documentation accordingly.
---
> feat: CheatSheet/HackBook | Add Responsive Design

- src/components/Dashboard/Profile/ConnectionsAndFollows/Connections/ConnectionElements.jsx
- src/components/Dashboard/Profile/ConnectionsAndFollows/ConnectionsAndFollows.jsx
- src/components/Dashboard/Profile/ConnectionsAndFollows/Follow/FollowElements.jsx
- src/components/Dashboard/Profile/UserLinks/UserLinks.jsx
- src/components/Dashboard/Profile/UserProfile.jsx
fixes issue #603 
- fixed the connection request overflow  
- add auth popup when clicking follow or connect and no user is logged in : 
although in this issue it was asked to show a login popup for non logged in users who click on follow , i added the same functionality for the connect button .
- [ x] By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/thecyberworld/Support/blob/main/CODE_OF_CONDUCT.md) 🖖
- [x ] My code follows the code style of this project.
- [x ] My change requires changes to the documentation.
- [x ] All new and existing tests passed.
- [x ] This PR does not contain plagiarized content.
- [x ] The title of my pull request is a short description of the requested changes.
---
You can also join our …
> feat: profile | auth popup on follow/connect when no user / connection request styling overflow

- src/App.jsx
- src/components/Common/DateDisplay/DateDisplay.jsx
- src/components/Common/DateDisplay/DateDisplayElements.jsx
- src/components/Common/DateDisplay/index.js
- src/components/CommunityEvents/CommunityEvents.jsx
- src/components/CommunityEvents/EventItemList.jsx
- src/components/CommunityEvents/EventItemListElement.jsx
- src/components/CommunityEvents/ParticipantsDisplay.jsx
- src/components/CommunityEvents/ParticipantsDisplayElement.jsx
- src/components/Header/Navbar/NavbarElements.jsx
- src/components/Opportunities/DisplayCommunityEvents/DisplayCommunityEventDetails.jsx
- src/components/Opportunities/DisplayCommunityEvents/DisplayCommunityEventDetailsElement.jsx
- src/components/Opportunities/DisplayCommunityEvents/index.js
- src/components/WebSecurity/SubHeaderElements.jsx
related to issue #564
https://github.com/thecyberworld/TheCyberHUB/assets/76536506/a493c41a-03ad-4d4d-9e56-eef61c72a3ee
Next time, I will work on the option to add / display timeline of speakers and activities which I will display in this page
---
> feat: community events | event details page

- src/components/WebSecurity/CodeReviews/CodeReview.jsx
- src/components/WebSecurity/Common/Labs/Labs.jsx
- src/components/WebSecurity/CrackMe/CrackMe.jsx
- src/components/WebSecurity/WebSecurityLabs/WebSecurityLabs.jsx
> fix: Web Security | sidebar icons 

- src/components/Dashboard/Analytics/AnalyticsBarChart.jsx
- src/components/Dashboard/Analytics/AnalyticsDoughnutChart.jsx
- src/components/Dashboard/Analytics/AnalyticsMainBarChart.jsx
why: Because Chart.js is an ESM library, in CommonJS modules you should use a dynamic import
---
> fix: to dynamic import

- src/components/WebSecurity/Common/Labs/Labs.jsx
- src/components/WebSecurity/Sidebar.jsx
- src/components/WebSecurity/SubHeader.jsx
- src/components/WebSecurity/WebSecurityTopics/Topics.jsx
closes #758 (edited)
1. Categories selected are now highlighted 
2. Current routes are now highlighted
()
---
> fix: web security | categories and route highlighting

- src/components/Dashboard/OldDashbaord/GoalSetter/GoalForm.jsx
Fixes #813 
Added font color to input text which matches website theme
I found some additional bugs that are on this page. Am I allowed to create issues for these? If not, can issues be created and may I please be assigned to them?
They are as follows:
The add button is overflowing outside the input box
There is heavy overflow on the goals that are added also
-   [x] …
> Added font coloring to GoalForm > GoalInput

- package-lock.json
- package.json
- src/components/Dashboard/Analytics/AnalyticsPageTopSectionMainContent.jsx
- src/components/Dashboard/Analytics/AnalyticsPageTopSectionMainContentElements.jsx
- src/components/Dashboard/Analytics/AnalyticsUtils.js
Fix #800 
Adding a CVS file that contains the analytic data (currently the data is coming from the jsons files) 
Go to the dashboard : 
Click here on the download button: 
Then you will be able to download this file: 
Currently, this is how the file displays the data : 
-   [X] By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/thecyberworld/TheCyberHUB/blob/dev/CODE_OF_CONDUCT.md) 🖖
-   [X] My code follows the code style of this project.
-   [X] All new and existing tests passed.
-   [X] This PR does not contain plagiarized content.
-   [X] The title of my pull request is a short description of the requested changes.
> Add functionality for download button

- package-lock.json
- src/components/Tools/EncoderDecoder.jsx/EncoderCode.jsx
- src/components/Tools/EncoderDecoder.jsx/EncoderCodeElement.jsx
Fixed #818;
Now we have a button to copy the encoded and decoded texts : 
https://github.com/thecyberworld/TheCyberHUB/assets/34707669/438a2608-4956-4be5-a867-a55b095e45b6
Please notice that I pushed the package lock because the dependencies of font awesome was needed but was missing from the file.
> Add copy button to encoded + decoded fields

- src/components/Common/SocialSidebar/SidebarElements.jsx
- src/components/Explore/ExploreElements.jsx
This PR fixes Search/Sidebar width not full in small screen
Closes #802
- Adjusted CSS in `LeftContainer` styled component to resolve responsiveness issues on smaller screen sizes in the Explore.jsx SideBarElements.jsx and ExploreElements.jsx page.
- Changed width properties and align properties for ExploreElements.jsx
Please review the changes made in SideBarElements.jsx and ExploreElements.jsx  to ensure that responsiveness is improved across different devices.
-   [x] My change requires changes to the documentation.
-   [x] I have updated the documentation accordingly. …
> [FIX] Fixed Search/Sidebar width not full in small screen
