th3cyb3rhub/TheCyberHUB

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/doc_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/ISSUE_TEMPLATE/other.yml
- .github/pull_request_template.md
- .github/workflows/community.yml
- .github/workflows/deploy.yml
- .github/workflows/release.yml
- pull_request_template.md
- src/components/Footer/Footer.jsx
---
You can also join our [Discord](https://discord.gg/QHBPq6xP5p) community. <br>
Feel free to check out other cool repositories of the [Cryptoverse Web3](https://github.com/CryptoverseWeb3). <br>
Join the Cryptoverse Web3 GitHub Organisation by raising an [issue](https://github.com/CryptoverseWeb3/Support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization) (you will be sent an invitation).
> add: Workflows actions template

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/doc_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/ISSUE_TEMPLATE/other.yml
- .github/pull_request_template.md
- .github/workflows/community.yml
- .github/workflows/deploy.yml
- .github/workflows/release.yml
- pull_request_template.md
- src/components/Buttons/ButtonElements.jsx
- src/components/Footer/Footer.jsx
- src/components/Homepage/Info/Data.jsx
- src/components/Homepage/Info/Info.jsx
- src/components/Homepage/Navbar/Navbar.jsx
- src/components/Homepage/Navbar/NavbarElements.jsx
- src/components/Homepage/Services/Services.jsx
- src/components/Homepage/Socials/Socials.jsx
- src/pages/Homepage.jsx
> Improvements 1

- package-lock.json
- package.json
- src/App.jsx
> fix: Redirect 404

- .github/FUNDING.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/workflows/deploy.yml
- CONTRIBUTING.md
- README.md
- pull_request_template.md
> feat: open-source

- src/App.jsx
- src/components/Courses.jsx
- src/components/Courses/Card/Card.css
- src/components/Courses/Card/Card.jsx
- src/components/Courses/Courses.jsx
- src/components/Courses/Sidebar/Sidebar.jsx
- src/components/Courses/Sidebar/SidebarElements.jsx
- src/components/Courses/YouTubeVideos.jsx
- src/components/Courses/YouTubeVideosElements.jsx
- src/components/Courses/YoutubeCourses.jsx
- src/components/Courses/YoutubeCoursesData/CyberSecYouTubeVIdeosData.jsx
- src/components/Courses/YoutubeCoursesData/LinuxYouTubeVIdeosData.jsx
- src/components/Courses/YoutubeCoursesNavbar/NavbarElements.jsx
- src/components/Courses/YoutubeCoursesNavbar/YoutubeCoursesNavbar.jsx
- src/components/Homepage/Info/Data.jsx
- src/main.jsx
[FEATURE] Free Courses #63 
closes #63 
---
> feat: courses

- src/App.jsx
- src/components/Courses.jsx
- src/components/Courses/Card/Card.css
- src/components/Courses/Card/Card.jsx
- src/components/Courses/Courses.jsx
- src/components/Courses/Sidebar/Sidebar.jsx
- src/components/Courses/Sidebar/SidebarElements.jsx
- src/components/Courses/YouTubeVideos.jsx
- src/components/Courses/YouTubeVideosElements.jsx
- src/components/Courses/YoutubeCourses.jsx
- src/components/Courses/YoutubeCoursesData/CyberSecYouTubeVIdeosData.jsx
- src/components/Courses/YoutubeCoursesData/LinuxYouTubeVIdeosData.jsx
- src/components/Courses/YoutubeCoursesNavbar/NavbarElements.jsx
- src/components/Courses/YoutubeCoursesNavbar/YoutubeCoursesNavbar.jsx
- src/components/Homepage/Info/Data.jsx
- src/main.jsx
- src/pages/Courses.jsx
> fix: courses

- src/App.jsx
- src/components/Contribute/Contribute.jsx
- src/components/Resources/CyberNews/CyberNews.jsx
- src/components/Resources/Resources.jsx
- src/components/Resources/ResourcesNavbar/ResourcesNavbar.jsx
- src/components/Resources/WriteUps/WriteUps.jsx
- src/components/Resources/WriteUps/WriteUpsElements.jsx
- src/pages/Resources.jsx
> feat: writeups

- src/components/Resources/WriteUps/WriteUps.jsx
- src/components/Resources/WriteUps/WriteUpsElements.jsx
> feat: write-ups

- src/components/Resources/WriteUps/WriteUps.jsx
- src/components/Resources/WriteUps/WriteUpsElements.jsx
> feat: write-up

- src/components/Resources/Courses/YouTubeVideosElements.jsx
- src/components/Resources/Courses/YoutubeCourses.jsx
- src/components/Resources/WriteUps/WriteUps.jsx
- src/components/Resources/WriteUps/WriteUpsElements.jsx
> fix-write-ups

- src/App.jsx
- src/components/Resources/Events/Events.jsx
- src/components/Resources/Jobs/Jobs.jsx
- src/components/Resources/ResourcesNavbar/ResourcesNavbar.jsx
- src/components/index.js
- src/pages/Resources.jsx
> fix: navigation

- 404.html
- index.html
> add: 404.html

- src/components/Resources/Courses/VideoCard/VideoCard.jsx
- src/components/Resources/Courses/VideoCard/VideoCardElements.jsx
- src/components/Resources/ResourcesHome/ResourcesHome.jsx
- src/components/Resources/ResourcesList.jsx
- src/components/Resources/ResourcesListElements.jsx
- src/components/Resources/WriteUps/WriteUpsElements.jsx
- src/pages/Resources.jsx
> feat: Resources List

- index.html
- src/components/Resources/Courses/VideoCard/VideoCard.jsx
- src/components/Resources/Courses/VideoCard/VideoCardElements.jsx
- src/components/Resources/ResourcesHome/ResourcesHome.jsx
- src/components/Resources/ResourcesList.jsx
- src/components/Resources/ResourcesListElements.jsx
- src/components/Resources/WriteUps/WriteUpsElements.jsx
- src/pages/Resources.jsx
> add: link image

- src/components/Buttons/ButtonElements.jsx
- src/components/Homepage/Navbar/Navbar.jsx
- src/components/Resources/ResourcesNavbar/NavbarElements.jsx
- src/components/Resources/ResourcesNavbar/ResourcesNavbar.jsx
- src/components/Resources/WriteUps/WriteUpsElements.jsx
> feat: share-us

- src/components/Resources/ResourcesHome/ResourcesHome.jsx
- src/components/Resources/ResourcesList.jsx
- src/components/Resources/ResourcesListElements.jsx
> add: Resources

- package-lock.json
- package.json
- src/App.jsx
- src/app/store.js
- src/components/Footer/Footer.jsx
- src/components/Resources/CyberNews/CyberNews.jsx
- src/components/Resources/CyberNews/CyberNewsElements.jsx
- src/components/Resources/ResourcesList.jsx
- src/components/Resources/ResourcesListElements.jsx
- src/main.jsx
- src/services/cyberNewsApi.js
> feat: Cyber news

- src/components/Resources/CyberNews/CyberNews.jsx
- src/components/Resources/CyberNews/Loader.jsx
- src/services/cyberNewsApi.js
> Cyber news

- package-lock.json
- package.json
- src/App.jsx
- src/Spinner/SpinnerElements.jsx
> feat: pre-loading spinner

- package-lock.json
- package.json
- src/App.jsx
- src/Spinner/SpinnerElements.jsx
> fix: loader spinner timestamp

- src/App.jsx
> fix: spinner timee

- src/App.jsx
> fix: spinner timestamps 5m

- src/components/Resources/ResourcesList.jsx
- src/components/Resources/ResourcesListElements.jsx
> add: cyber security roadmap

- src/App.jsx
- src/components/MixComponenets/Spinner/Spinner.jsx
> fix: spinner struct

- src/App.jsx
- src/components/Homepage/Dropdowns/Dropdown.jsx
- src/components/Homepage/Dropdowns/SideDropdown.jsx
- src/components/Homepage/Navbar/Navbar.jsx
- src/components/Homepage/Navbar/NavbarElements.jsx
- src/components/Homepage/Sidebar/Sidebar.jsx
- src/pages/Homepage.jsx
- src/pages/Prep.jsx
- src/pages/Resources.jsx
> fix: navbar design

- src/components/Resources/Blogs/Blog.css
- src/components/Resources/Blogs/BlogsElements.jsx
Closes #142
Updates the blog entry container to a max-width of 400px to a max-width of 400px to make sure it doesn't try to take up 400px on smaller screens. Also updated the image width and height to 100% and auto to make the image fit the container in width and still look good with height auto
---
> Fix blog entry overflow on mobile

- index.html
there is extra space  in cyber security.
Closes #156 
Removed extra space between words, which are forming deformilities.
---
> fix: Remove extra space

- src/components/Homepage/Info/Data.jsx
> fix: homepage design

- src/components/Homepage/Info/Data.jsx
> Fix homepage design

- src/components/Resources/RoadmapResources/RoadmapResources.jsx
> add: html and sql resources for beginners to learn

- src/components/Homepage/Info/InfoElements.jsx
> add: fix design and icons

- src/components/Homepage/Info/Data.jsx
> fix: data.jsx

- src/components/Resources/Blogs/AllBlogs.jsx
- src/components/Resources/Blogs/Blogs.jsx
- src/components/Resources/Blogs/ViewBlog.jsx
- src/components/Resources/Blogs/util.js
Closes: #155 
Changed the URL Structure of blogs
**From:**
```
https://www.thecyberhub.org/blogs/viewBlog?id=1
```
**To:**
```
https://www.thecyberhub.org/blogs/viewBlog/What-is-Docker
```
Please review the changes.
---
> URL format changed for blogs

- src/components/Resources/Blogs/Blog.css
Closes #143 
This fixes the Blog section responsivity.
Below are videos of the `blog section` in Desktop, Tablet and Mobile view:
`Desktop view:`
https://user-images.githubusercontent.com/94648837/194900300-5f810c7f-066b-4a5c-9402-5f5a05452999.mov
`Tablet view:`
https://user-images.githubusercontent.com/94648837/194900343-ddb8263f-60fc-4970-aa06-99368ba81418.mov
`Mobiel view:`
https://user-images.githubusercontent.com/94648837/194900384-c93ebfe1-e979-4ba0-acd7-2943ef2da200.mov
> fix the responsiveness of the blogs

- .gitignore
- src/components/Events/EventsHeader.css
- src/components/Events/EventsHeader.jsx
> fix: events header

- src/components/Resources/RoadmapResources/RoadmapResources.jsx
> fix: resources url bug

- src/components/Homepage/Info/Info.jsx
> fix: nav route

- src/components/Navbar/Navbar/Navbar.jsx
there is nothing in the navitem
and the about section is already on the homepage. so there is no need to create an another extra page for the same thing
- there is nothing in the navitem
and the about section is already on the homepage. so there is no need to create an another extra page for the same thing
---
> fix: about nav-item

- package-lock.json
- src/components/Events/Events.jsx
> fix: Event Date Issue Resolved

- package-lock.json
- package.json
- src/App.jsx
- src/components/Homepage/Hero/Hero.jsx
- src/components/MixComponents/Spinner/Spinner.jsx
> add: spinners

- package-lock.json
- package.json
- src/components/Navbar/Dropdowns/Dropdown.jsx
- src/components/Resources/CyberNews/CyberNews.jsx
- src/services/cyberNewsApi.js
Closes #98 
- fixed routing issue for News Section
- added infinite scroll for News
[recording-2022-10-16-20-05-36.webm](https://user-images.githubusercontent.com/43086476/196041520-83225960-ee63-44cc-a85a-caa67d6ce490.webm)
---
> Infinite scroll news

- src/components/Prep/Jobs/Jobs.jsx
> fix: typo in the jobs page

- src/components/Resources/CyberNews/CyberNewsElements.jsx
fix: improve layout and readability of NEWS
now: 
before: ![image](https://user-images.githubusercontent.com/115712204/196052240-cfd07cab-ffc0-467e-9850-0aa8f4454aa9.png)
---
> improve layout and readability of NEWS

- src/components/Prep/Jobs/Jobs.jsx
> fix: typo Jobs.jsx

- src/components/Events/PastEvents/PastEventsElements.jsx
> fix: alignments

- src/components/Homepage/Info/Data.jsx
> fix: homepage buttons

- src/components/Resources/Blogs/BlogsElements.jsx
> fix: typo in blogs

- src/components/Events/EventsElement.jsx
> fix: miss-alignment of the events

- src/components/Navbar/Dropdowns/Dropdown.jsx
- src/components/Navbar/Dropdowns/DropdownElements.jsx
- src/components/Navbar/Navbar/Navbar.jsx
- src/components/Navbar/Navbar/NavbarElements.jsx
- src/components/Navbar/Sidebar/SidebarElements.jsx
> feat: transparent drop navbar

- package.json
> fix: deploy and build issues

- src/main.jsx
> fix: deploy issues: main.jsx rendring

- src/components/Homepage/Hero/Hero.jsx
> add: videos and images (cloud to local)

- src/components/Homepage/Info/Data.jsx
> fix: logo url (cloud to local files)

- src/App.jsx
- src/components/Learn/Courses/YouTubeVideosElements.jsx
- src/components/Learn/Courses/YoutubeCourseDetail.jsx
- src/components/Learn/Courses/YoutubeCourses.jsx
- src/components/Learn/Courses/YoutubeCoursesLayout.jsx
- src/components/Learn/Courses/YoutubeCoursesSidebar.jsx
- src/components/index.js
- src/pages/Resources.jsx
Closes #221 
Added routing to the course page and a sidebar to navigate to get particular courses.
https://user-images.githubusercontent.com/41188167/197024086-6d4c96f9-cf83-4fdc-a2ee-6ca214673254.mov
> feat: Added routing and sidebox on the course page

- src/components/Prep/Jobs/JobsData.jsx
- src/components/Prep/Jobs/JobsElements.jsx
Closes #200
jobs layout remains the same whether zoom in or out.
Before changes
After changes
---
> fix: jobs layout

- src/components/Navbar/Dropdowns/Dropdown.jsx
- src/components/Navbar/Navbar/Navbar.jsx
Closes #230 
* After clicking on the Navitem, the Navbar should be closed but the navbar dropdown is still open
---
> Navbar still remain open Bug Fixed

- src/components/Prep/Jobs/Jobs.jsx
- src/components/Prep/Jobs/JobsElements.jsx
Closes #246
buttons related content removed
after changes
> Remove dropdown icon

- src/components/Navbar/Dropdowns/DropdownElements.jsx
Closes #247
- overflowing of Menu Items at zoom-in.
- layout of Menu Items
- overflown of menu items at zoom-in
- layout of Menu Items
> fix: navbar overflow and menu items layout

- src/App.jsx
- src/components/Certificate/Certificate.jsx
- src/components/Certificate/CertificateElements.jsx
- src/components/Certificate/certificate.scss
- src/components/CyberGames/CTF/CTF.jsx
- src/components/CyberGames/CTF/CTFData.jsx
- src/components/CyberGames/CTF/CTFElements.jsx
> feat: input func to get certificate

- src/components/Navbar/Navbar/NavbarElements.jsx
Closes #258
Before changes
After changes
> fix:navbar menu items collision with each other

- src/components/Resources/Jobs/Job.jsx
- src/components/Resources/Jobs/JobsData.jsx
- src/components/Resources/Jobs/JobsElements.jsx
> add: jobs section page and layout (+ improve data structure)

- src/components/Resources/CyberNews/CyberNews.jsx
- src/components/Resources/CyberNews/CyberNewsElements.jsx
> feat: news sections page and improve user visibility

- src/components/Resources/Quiz/Categories/CBQ/CBQ.jsx
- src/components/Resources/Quiz/Categories/CategoriesButtonData.jsx
- src/components/Resources/Quiz/Categories/CategoriesButtons.jsx
- src/components/Resources/Quiz/Categories/CategoriesElements.jsx
- src/components/Resources/Quiz/Categories/PSQ/PSQ.jsx
- src/components/Resources/Quiz/Categories/Phishing/Phishing.jsx
- src/components/Resources/Quiz/Categories/Ransomware/Ransomeware.jsx
- src/components/Resources/Quiz/Categories/SRAQ/SRAQ.jsx
- src/components/Resources/Quiz/Categories/TSSQ/TSSQ.jsx
- src/components/Resources/Quiz/Categories/VSQ/VSQ.jsx
- src/utils/components/RenderProgressIndicator.jsx
Closes #189 
- redesign quiz section
- abbreviate labels of `<CategoriesButtons />` 
- fix uneven width between buttons and the quiz body
- add reusable utility component to render the progress indicator across categories in a new `utils/components` directory
https://user-images.githubusercontent.com/93228906/198066172-04510467-545b-460e-844f-d32434d5627e.mp4
There seems to be a lot of repetition in the `src/components/Resources/Quiz/Categories/` components. I didn't dig deep or bother refactoring cause I didn't want to go out of scope but maybe I could open a separate issue on it?
---
Join the Thecyberworld …
> feat [#189]: redesign quiz section

- src/components/Footer/Footer.jsx
- src/components/Homepage/Info/Data.jsx
- src/components/MixComponents/Spinner/Spinner.jsx
We had a few issues in the console before this PR:
But now the console looks clean! ![console](https://user-images.githubusercontent.com/6019047/199137999-75672f8a-0adb-49ad-9499-8b1c852559b5.png)
- [ x ] By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/thecyberworld/Support/blob/main/CODE_OF_CONDUCT.md) 🖖
- [ x ] My code follows the code style of this project.
- [ x ] All new and existing tests passed.
- [ x ] This PR does not contain plagiarized content.
- [ x ] The title of my pull request is a short description of the changes.
> Fixing issues appearing in the console

- src/App.jsx
- src/components/CyberGames/CTF/CTFData.jsx
- src/components/Learn/Blogs/util.js
- src/components/Learn/Roadmaps/Roadmap.jsx
- src/components/Navbar/Navbar/Navbar.jsx
- src/components/Navbar/Sidebar/Sidebar.jsx
- src/components/Resources/Events/Event.jsx
- src/components/Resources/Events/Events.jsx
- src/components/Resources/Events/EventsElement.jsx
- src/components/Resources/WriteUps/WriteUpsElements.jsx
- src/components/index.js
> add: view events

- src/App.css
- src/components/Learn/Blogs/Blogs.jsx
- src/components/Learn/Blogs/ViewBlog.jsx
- src/components/Navbar/Dropdowns/DropdownElements.jsx
- src/components/Resources/Events/Events.jsx
- src/components/Resources/Events/EventsElement.jsx
- src/components/Resources/Events/OnGoingEvents/OnGoingEventsElements.jsx
- src/components/Resources/Events/ViewEvent/Event.jsx
> fix: exents and navbar

- src/components/Community/Community.jsx
- src/components/Community/CommunityElements.jsx
> fix: community design

- src/components/Resources/Events/Events.jsx
> fix: CTF data

- index.html
- src/App.jsx
- src/components/Homepage/Navbar/Navbar/Navbar.jsx
- src/components/Homepage/Navbar/Sidebar/Sidebar.jsx
- src/components/Sponsors/Sponsors.jsx
- src/components/Sponsors/SponsorsElements.jsx
- src/components/index.js
> add: sponsors

- src/components/Homepage/Info/Data.jsx
> fix: roadmaps home link 

- src/components/Homepage/Info/Info.jsx
> fix: roadmaps home link

- package-lock.json
- src/components/Homepage/Navbar/Dropdowns/Dropdown.jsx
- src/components/Homepage/Navbar/Dropdowns/DropdownElements.jsx
- src/components/Homepage/Navbar/Sidebar/Sidebar.jsx
- src/components/Homepage/Navbar/Sidebar/SidebarElements.jsx
> Sidebar Fixed

- src/components/Homepage/Navbar/Dropdowns/DropdownElements.jsx
- src/components/Homepage/Navbar/Navbar/NavbarElements.jsx
- src/components/Learn/Roadmaps/Roadmap.jsx
- src/components/Learn/Roadmaps/RoadmapElements.jsx
> fix: nonresponsive roadmap #314 and fix navbar issue in different browser

- src/components/Learn/Roadmaps/RoadmapElements.jsx
> fix: design of roadmap

- src/App.jsx
- src/components/Dashboard/Streak/Streak.jsx
- src/components/Header/Dropdowns/Dropdown.jsx
- src/components/Header/Navbar/Navbar.jsx
- src/components/LearningPath/LearningPath.jsx
- src/components/LearningPath/LearningPathData.jsx
- src/components/LearningPath/LearningPathElements.jsx
> feat: learning path

- package-lock.json
- package.json
- src/App.jsx
- src/components/Blogs/Blogs.jsx
- src/components/Dashboard/BlogSetter/BlogCard.jsx
- src/components/Dashboard/BlogSetter/CreateBlog/CreateBlog.jsx
- src/components/Dashboard/BlogSetter/CreateBlog/CreateBlogElements.jsx
- src/components/Dashboard/BlogSetter/Tags/Tags.jsx
- src/components/Dashboard/BlogSetter/UserBlogs.jsx
- src/components/Dashboard/BlogSetter/ViewBlog/ViewBlog.jsx
- src/components/Dashboard/BlogSetter/ViewBlog/ViewBlogElements.jsx
> add: markdown blog

- Dockerfile
- src/components/Dashboard/BlogSetter/AddComments.jsx
- src/components/Dashboard/BlogSetter/BlogCardElements.jsx
- src/components/Dashboard/BlogSetter/ViewBlog/ViewBlog.jsx
- src/components/Dashboard/BlogSetter/ViewBlog/ViewBlogElements.jsx
- src/components/Header/Navbar/NavbarElements.jsx
- src/features/blogs/blogService.js
- src/features/blogs/blogSlice.js
> feat: blog comments

- src/App.jsx
- src/components/Certificate/CertificateCard.jsx
- src/components/Certificate/CertificateElements.jsx
- src/components/Certificate/CertificatePage.jsx
> add: CertificateCard

- src/components/CyberGames/CTF/CTF.jsx
- src/components/Dashboard/BlogSetter/EditBlog/EditBlog.jsx
- src/features/blogs/blogService.js
- src/features/blogs/blogSlice.js
Closes #330 
-FIX: the server is using the "PUT" method instead of "PATCH" in update blog route.
-These changes fixes thunkAPI being undefined.
**Bugs Found (related to update blog):**
---
> fix: Updating Blog is not working

- src/components/Dashboard/BlogSetter/BlogSidebar/LeftBlogSidebar.jsx
- src/components/Dashboard/BlogSetter/BlogSidebar/LeftBlogSidebarElements.jsx
- src/components/Dashboard/BlogSetter/BlogSidebar/RightBlogSidebarElements.jsx
- src/components/Dashboard/BlogSetter/Blogs.jsx
- src/components/Dashboard/BlogSetter/BlogsElements.jsx
- src/components/Dashboard/BlogSetter/UserBlogs.jsx
- src/components/Dashboard/Profile/Profile.jsx
- src/components/Learn/Roadmaps/RoadmapsElements.jsx
- src/features/auth/authService.js
- src/features/blogs/blogService.js
- src/features/goals/goalService.js
- src/features/userDetails/userDetailService.js
> fix: border green color blogs

- package-lock.json
- src/App.jsx
- src/components/Blogs/Blogs.jsx
- src/components/Forum/Card.jsx
- src/components/Forum/CardElements.jsx
- src/components/Forum/Forum.jsx
- src/components/Forum/ForumData.jsx
- src/components/Forum/ForumElements.jsx
- src/components/Forum/ViewQuestion.jsx
- src/components/Forum/ViewQuestionElements.jsx
- src/components/Header/Navbar/Navbar.jsx
- src/components/Tools/ToolsElements.jsx
> feat: Forums

- src/components/Blogs/Comments/ViewComments.jsx
> fix: user comment picture

- package.json
- src/components/Other/Certificate/CertificateCard.jsx
- src/components/Other/Certificate/CertificateElements.jsx
> feat: download certificate

- src/App.jsx
- src/components/Dashboard/DashboardItems.jsx
- src/components/Dashboard/EmailNotVerified.jsx
- src/components/Dashboard/EmailNotVerifiedElements.jsx
- src/components/Dashboard/GoalSetter/GoalSetter.jsx
- src/components/Dashboard/Profile/Profile.jsx
- src/components/Header/Navbar/Navbar.jsx
> add: email verification

- src/App.jsx
- src/components/Resources/Jobs/JobsData.jsx
> add: contact form and design

- index.html
- src/App.jsx
- src/components/ContactForm/ContactForm.jsx
- src/components/ContactForm/ContactFormElements.jsx
- src/components/Resources/Jobs/JobsData.jsx
> fix: improvements

- src/components/Header/Navbar/Navbar.jsx
- src/components/Header/Navbar/NavbarElements.jsx
- src/components/Header/Sidebar/Sidebar.jsx
> feat: security courses

- src/components/Other/Certificate/CertificateCard.jsx
- src/components/Other/Certificate/CertificateElements.jsx
> feat: new cert design

- package-lock.json
- src/components/Header/UserOptions/UserOptions.jsx
Closes #384 
Once the profile dropdown is clicked, it should close if the website is scrolled or on a mouse click, anywhere in the active window.
---
> Fix: Added listener to close user option

- package-lock.json
- src/components/Header/UserOptions/UserOptions.jsx
> fix: auto close user option dropdown (#385)

- src/components/Beta/Tools/SubdomainFinder/SubdomainFinderElements.jsx
> fix: subfinder design

- src/components/Beta/Tools/SubdomainFinder/SubdomainFinderElements.jsx
- src/components/Blogs/BlogCard/NewBlogCardElements.jsx
- src/components/Blogs/ViewBlog/ViewBlogElements.jsx
- src/components/Header/Dropdowns/Dropdown.jsx
- src/components/Header/Dropdowns/DropdownElements.jsx
- src/components/Header/Sidebar/Sidebar.jsx
> Fix responsive

- src/components/Blogs/BlogCard/NewBlogCardElements.jsx
- src/components/Dashboard/Profile/UserProfile.jsx
- src/features/userDetail/userDetailService.js
> fix: blogs heading

- .dockerignore
- src/App.jsx
- src/components/Blogs/Blogs.jsx
- src/components/Header/Navbar/Navbar.jsx
- src/components/Homepage/Footer/Footer.jsx
- src/components/Resources/InterviewQuestions/InterviewQuestions.jsx
- src/components/Resources/InterviewQuestions/InterviewQuestionsElements.jsx
- src/components/Security/HallOfFame.jsx
- src/components/Security/HallOfFameElements.jsx
- src/components/Security/RulesOfEngagement.jsx
- src/components/Security/RulesOfEngagementElements.jsx
- src/components/Security/Security.jsx
- src/components/Security/SecurityElements.jsx
- src/components/Security/SecurityNavigation.jsx
> feat: security page

- index.html
- src/components/Blogs/BlogComments/ViewComments.jsx
- src/components/Dashboard/Profile/EditPublicProfile/EditUserLinks.jsx
- src/components/Dashboard/Profile/UserLinks/UserLinks.jsx
- src/components/Explore/Users/Users.jsx
- src/components/Feeds/FeedComments/AddFeedComment.jsx
- src/components/Feeds/FeedComments/ReplyCard.jsx
- src/components/Feeds/FeedComments/ViewFeedComments.jsx
- src/components/Feeds/FeedPage/FeedPage.jsx
- src/components/Feeds/FeedPage/FeedPagePost.jsx
- src/components/Feeds/FeedPosts/FeedPost.jsx
- src/components/Feeds/Feeds.jsx
- src/components/Feeds/PostForm/AddFeed.jsx
> feat: blogs feeds explore and design

- src/components/CaptureTheFlag/SingleCTF/CtfRegister.jsx
- src/components/CaptureTheFlag/SingleCTF/SingleCTF.jsx
- src/components/CaptureTheFlag/SingleCTF/SingleCTFElements.jsx
- src/features/ctf/ctfSlice.js
- src/main.jsx
> fix: ctf and certificate minor issues

- src/components/CaptureTheFlag/SingleCTF/CtfTeam.jsx
- src/components/CaptureTheFlag/SingleCTF/CtfTimeToStart.jsx
- src/components/CaptureTheFlag/SingleCTF/LikesAndViews.jsx
- src/components/CaptureTheFlag/SingleCTF/SingleCTF.jsx
- src/main.jsx
> fix: ctf minor issues

- src/components/Blogs/ViewBlog/ViewBlog.jsx
- src/components/Dashboard/Profile/UserLinks/UserLinks.jsx
- src/components/Forum/CreateForumPost/CreateForumPost.jsx
- src/components/Header/Navbar/Navbar.jsx
- src/main.jsx
> fix: minor issues

- src/components/Homepage/Socials/Socials.jsx
Fix Spelling Mistake in Socials.jsx
---
> fix: Spelling Mistake

- package-lock.json
- src/components/Homepage/ContactForm/ContactForm.jsx
Message icon is in middle in mobile version issue - #443
---
> fix: Message icon is in middle in mobile version issue - #443

- src/components/Homepage/Footer/FooterElements.jsx
Fixed social icons over flows in footer box when moble view 
Close #445 
below 600px screen set padding 24px on FooterContainer in FooterElements.jsx
---
> fix: icons over flow in footer

- README.md
- example.env
> fix: ReadMe.md

- src/components/Other/Certificate/CertificateCard.jsx
- src/components/Other/Certificate/CertificateElements.jsx
- src/main.jsx
Added option to share certificate on X(twitter) and Linkedin
Currently only the link is shared when sharing on social platforms . I am working on sharing certificate image as well.
- [x ] My code follows the code style of this project.
---
> feat: option to share certificate on socials.

- src/components/CaptureTheFlag/CTF.jsx
- src/components/Dashboard/Profile/UserPoints/UserPoints.jsx
- src/components/Dashboard/Profile/UserPoints/UserPointsElements.jsx
- src/components/Header/Navbar/NavbarElements.jsx
- src/components/Other/CyberGames/Leaderboard/Leaderboard.jsx
- src/components/Other/CyberGames/Leaderboard/LeaderboardElements.jsx
Closes #467
The leaderboard table is refined with UX in mind, letting the table columns **Rank** and **Users** be aligned at the start which increases the readability, the column **Points** is right aligned as it will be easier for users to compare the values with other users. Additionally, I added a **hover effect on table row**  which will increase readability. Padding in the **x-axis** in the table body is fixed.
- Added two styled-components
1. LeaderboardTableHeaderPoints
2. LeaderboardTablePoints
- Added hover effect on a table row
- Added text-align to start for **Rank** and **Users** column and text-align to right for **Points** column
- Padding on **x-axis** fixed for table body rows
---
Feel free to check …
> feat: Leaderboard design Improvement

- src/components/Header/Navbar/NavbarElements.jsx
closes #485 
I fix the alignement in CSS, there is margin 5px in the top that cause the alignement issue. You can see the fix with the screenshot bellow
---
> closes #485 : Fix alignement of icon and text in the navbar

- src/App.jsx
Closes #462 
Add overflow hidden when menu is open so the bg will not be Scrollable
https://github.com/thecyberworld/TheCyberHUB/assets/76536506/b5845d3c-6530-4f60-ade3-0bb3562ef4b2
---
> fix: When Menu Is Open Fix Scrollable Background

- src/components/ChatBot/ActionProvider.jsx
- src/components/ChatBot/MessageParser.jsx
- src/components/ChatBot/config.jsx
> fix: chatbot minor issues

- README.md
- src/App.jsx
- src/components/Blogs/Blogs.jsx
- src/components/Dashboard/Profile/UserProfile.jsx
- src/components/Dashboard/Sidebar/Sidebar.jsx
- src/components/Dashboard/Sidebar/SidebarElements.jsx
- src/components/Explore/Users/Users.jsx
- src/components/Explore/Users/UsersElements.jsx
- src/components/Feeds/FeedPage/FeedPagePost.jsx
- src/components/Feeds/FeedPosts/FeedPost.jsx
- src/components/Feeds/FeedPosts/FeedPostsElements.jsx
> fix: feed post design

- README.md
> fix: installtion method in README.md

- src/components/Dashboard/Notetaker/NoteApp.css
- src/components/Dashboard/Notetaker/NoteApp.jsx
- src/components/Dashboard/Notetaker/NoteDescription.jsx
- src/components/Dashboard/Notetaker/NoteElements.jsx
- src/components/Dashboard/Notetaker/NoteItem.jsx
- src/components/Dashboard/Notetaker/NoteList.jsx
- src/components/Dashboard/Notetaker/NotePinning.jsx
- src/components/Dashboard/Sidebar/SidebarElements.jsx
Related to issue #474 
##Screenshots
https://github.com/thecyberworld/TheCyberHUB/assets/76536506/a696da69-1ffc-4ce2-8eea-b0b304d465de
Still left to do in next pr's
---
> feat: notes taking app - pin and delete functionality

- src/components/Tools/ReverseShell/Main.jsx
- src/components/Tools/ReverseShell/ReveseShellElement.jsx
- src/components/Tools/Tools.jsx
- src/components/Tools/ToolsRoute.jsx
> Add reverse shell

- package-lock.json
- package.json
- src/components/Common/InputEditor/InputEditor.jsx
- src/components/Common/InputEditor/InputEditorElements.jsx
- src/components/Common/InputEditor/index.jsx
- src/components/Common/MarkdownEditor/MarkdownEditor.css
- src/components/Common/MarkdownEditor/MarkdownEditor.jsx
- src/components/Common/MarkdownEditor/MarkdownEditorElements.jsx
- src/components/Common/MarkdownEditor/index.jsx
- src/components/Dashboard/Notetaker/NoteApp.css
- src/components/Dashboard/Notetaker/NoteApp.jsx
- src/components/Dashboard/Notetaker/NoteDescription.jsx
- src/components/Dashboard/Notetaker/NoteElements.jsx
- src/components/Dashboard/Notetaker/NoteItem.jsx
Related to #474
https://github.com/thecyberworld/TheCyberHUB/assets/76536506/4dc25978-01eb-490f-884e-7f02ccdf3c9f
As you can see the "save" button only closes the editor.
For next pr, I am going to add 'notes' state management also in the Redux and then I will do the 'save' button for create/edit note.
---
> Feat/Note App Markdown Editor

- src/components/Feeds/FeedTags/FeedTags.jsx
- src/components/Feeds/FeedTags/FeedTagsElements.jsx
- src/components/Feeds/Feeds.jsx
- src/components/Feeds/FeedsElements.jsx
> feat: FeedTags

- src/components/Common/MarkdownEditor/CheckBoxClickable.jsx
- src/components/Common/MarkdownEditor/useImageUploadEvents.jsx
- src/components/Common/SearchInputBox/SearchInputBox.jsx
- src/components/Common/SearchInputBox/SearchInputBoxElements.jsx
- src/components/Dashboard/Notetaker/NoteApp.jsx
- src/components/Dashboard/Notetaker/NoteElements.jsx
- src/components/Dashboard/Notetaker/NoteItem.jsx
- src/components/Dashboard/Notetaker/NoteList.jsx
- src/components/Feeds/Feeds.jsx
https://github.com/thecyberworld/TheCyberHUB/assets/76536506/ab8e5481-e2d2-4ac2-9a03-0d29fa6ed8ed
I showed the notes section to my sister and she suggested some improvements :)
some tasks that we need to fix:
---
> feat: notes | some more tweaks

- src/components/Dashboard/DashboardRoute.jsx
- src/components/Dashboard/Sidebar/Sidebar.jsx
- src/components/Dashboard/Sidebar/SidebarElements.jsx
> feat: dasboard | design improvement

- src/App.jsx
- src/components/Chat/Chat.jsx
- src/components/Chat/Sidebar/Sidebar.jsx
- src/components/Common/InputEditor/InputEditor.jsx
- src/components/Common/InputEditor/InputEditorElements.jsx
- src/components/Common/MarkdownEditor/MarkdownEditor.jsx
- src/components/Common/MarkdownEditor/MarkdownEditorElements.jsx
- src/components/Common/SearchInputBox/SearchInputBoxElements.jsx
- src/components/Dashboard/DashboardRoute.jsx
- src/components/Dashboard/Notetaker/NoteApp.css
- src/components/Dashboard/Notetaker/NoteApp.jsx
- src/components/Dashboard/Notetaker/NoteDescription.jsx
- src/components/Dashboard/Notetaker/NoteElements.jsx
- src/components/Dashboard/Notetaker/NoteItem.jsx
- src/components/Dashboard/Notetaker/NotePinning.jsx
- src/components/Dashboard/Sidebar/Sidebar.jsx
- src/components/Dashboard/Sidebar/SidebarElements.jsx
- src/features/isAuthenticated.jsx
> feat: notes | new design

- src/components/Dashboard/Notetaker/NoteApp.jsx
- src/components/Dashboard/Notetaker/NoteDescription.jsx
- src/components/Dashboard/Notetaker/NoteElements.jsx
https://github.com/thecyberworld/TheCyberHUB/assets/76536506/57cdbc42-0950-4666-a18e-aecc561266f2
You can see in the video that the check boxes are not functional in the right side of the edit mode, do you want to change it?
---
> fix: notes | hide title description and pick first note by default

- src/app/store.js
- src/components/Dashboard/Notetaker/Category/CategoryElements.jsx
- src/components/Dashboard/Notetaker/Category/CategoryItem.jsx
- src/components/Dashboard/Notetaker/Category/CategoryList.jsx
- src/components/Dashboard/Notetaker/Category/CategorySidebar.jsx
- src/components/Dashboard/Notetaker/Category/CreateCategory.jsx
- src/components/Dashboard/Notetaker/Category/ModifyCategory.jsx
- src/components/Dashboard/Notetaker/NoteApp.css
- src/components/Dashboard/Notetaker/NoteApp.jsx
- src/components/Dashboard/Notetaker/NoteDescription.jsx
- src/components/Dashboard/Notetaker/NoteElements.jsx
- src/features/notes/category/categorySlice.js
https://github.com/thecyberworld/TheCyberHUB/assets/76536506/742e5f9d-371d-4abb-981c-bfc9dc1d070a
More to do:
---
> feat: notes | categories create/edit/remove

- src/App.jsx
- src/components/AIChat/AIChat.jsx
- src/components/AIChat/AIChatElements.jsx
- src/components/AIChat/ChatMessages.jsx
- src/components/AIChat/RecentChats.jsx
- src/components/AIChat/RecentChatsElements.jsx
- src/components/Dashboard/OldDashbaord/GoalSetter/GoalSetter.css
- src/components/Header/Navbar/Navbar.jsx
> feat: ai chat app

- src/components/AIChat/AIChat.jsx
- src/components/AIChat/AIChatElements.jsx
- src/components/AIChat/RecentChats.jsx
> fix: ai chat app | minor issues

- src/components/Dashboard/Notetaker/Category/CategoryElements.jsx
- src/components/Dashboard/Notetaker/Category/CategoryItem.jsx
- src/components/Dashboard/Notetaker/Category/CategoryList.jsx
- src/components/Dashboard/Notetaker/Category/CategorySidebar.jsx
- src/components/Dashboard/Notetaker/Category/ModifyCategory.jsx
- src/components/Dashboard/Notetaker/NoteApp.css
- src/components/Dashboard/Notetaker/NoteApp.jsx
- src/components/Dashboard/Notetaker/NoteDescription.jsx
- src/components/Dashboard/Notetaker/NoteSidebar.jsx
- src/components/Tools/ReverseShell/ShellGenerator.jsx
https://github.com/thecyberworld/TheCyberHUB/assets/76536506/a81cc26a-9ecc-4049-8444-4ec2de3127bc
---
> feat: notes | Change the CRUD Category UI, Leave One Required Category

- src/App.css
Closes #565
App.css file has been updated. New code added in order to hide the unexpected scrollbar buttons.
Please check out the changes.
- [✔] By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/thecyberworld/Support/blob/main/CODE_OF_CONDUCT.md) 🖖
- [✔] My code follows the code style of this project.
- [✔] All new and existing tests passed.
- [✔] This PR does not contain plagiarized content.
- [✔] The title of my pull request is a short description of the requested changes.
--- …
> Scrollbar buttons are removed

- src/components/AdminDashboard/AdminDashboardRoute.jsx
- src/components/Header/UserOptions/UserOptions.jsx
small but important change.
Why: only userType of "admin" or "team" can access the AdminDashboard
How: render this tab only for right users, redirect for other users
https://github.com/thecyberworld/TheCyberHUB/assets/76536506/22e6ecab-6241-48c7-8f81-21a56411edb0
---
> feat: AdminDashboard | Protect The AdminDashboard Route

- src/components/CommunityEvents/CommunityEvents.jsx
- src/components/CommunityEvents/CommunityEventsElement.jsx
- src/components/CommunityEvents/EventItemList.jsx
- src/components/CommunityEvents/EventItemListElement.jsx
- src/components/CommunityEvents/events.json
- src/components/Opportunities/DisplayCommunityEvents/DisplayCommunityEvents.jsx
- src/features/userDetail/userDetailSlice.js
How: using react and temporary storing the events that was picked in some state in redux later will change in right obj data Why: so the user could join and see the status of it in the page
related to issue #564
https://github.com/thecyberworld/TheCyberHUB/assets/76536506/c9a93068-65be-4877-addf-f8295203b68f
for next:
---
> feat: community events | Make The Displayed CommunityEvents Functional

- src/App.jsx
- src/components/Courses/Courses.jsx
- src/components/Courses/NewCourses/Course.jsx
- src/components/Courses/NewCourses/CoursesData.jsx
- src/components/Courses/NewCourses/NewCourses.jsx
- src/components/Resources/Quiz/Categories/Categories.jsx
- src/components/Resources/Quiz/Categories/QuizPage.jsx
> New course UI

- src/components/CaptureTheFlag/SingleCTF/Submission.jsx
- src/components/Feeds/FeedPosts/FeedPosts.jsx
- src/components/Feeds/Feeds.jsx
The search is now working for username, tags and caption.
---
> fix: feeds search bug fixed

- src/components/Homepage/ContactForm/ContactForm.jsx
conatact form fixed for feedback and other by just changing some if else conditions.
---
> fix: contact form fixed for feedback and other

- src/components/CaptureTheFlag/SingleCTF/Submission.jsx
Closes #466 
Submit button issue fixed.
---
> fix: submit button state fixed

- src/App.jsx
- src/components/Courses/Courses.jsx
- src/components/Courses/NewCourses/Course.jsx
- src/components/Courses/NewCourses/NewCourses.jsx
- src/components/Learn/Courses/VideoCard/VideoCardElements.jsx
- src/components/Resources/Quiz/Categories/QuizPage.jsx
> fix: quiz issues

- package-lock.json
- package.json
- src/components/Chat/CommunityChat.jsx
- src/components/Chat/encryptData.js
Now all the chat messages will be transferred in encrypted form between frontend and backend.
---
> feat: encrypted message transfer

- src/components/Other/MixComponents/Buttons/ButtonElements.jsx
#597 
Changed display property of IconSpacing to flex so GitHub Icon is now aligned 
- [] The title of my pull request is a short description of the requested changes.
---
> style: Update IconSpacing

- README.md
- src/components/Other/Security/HallOfFame.jsx
- src/components/Other/Security/HallOfFameElements.jsx
- src/components/Other/Security/RulesOfEngagement.jsx
- src/components/Other/Security/Security.jsx
- src/components/Other/Support/SponsorsElements.jsx
> fix: readme

- src/components/Header/Sidebar/SidebarElements.jsx
Closes #590
I have fixed the Element Over Menu Header issue by adjusting the styling.
Desktop
Tablet
Mobile
---
> fix: Element Over Menu Header issue

- src/components/AdminDashboard/ManageCommunityEvents/ManageCommunityEvents.jsx
- src/components/AdminDashboard/ManageCommunityEvents/ManageCommunityEventsElements.jsx
- src/components/Common/GeneralDashboardSidebar/GeneralDashboardSidebarElements.jsx
- src/components/CommunityEvents/CommunityEvents.jsx
- src/components/CommunityEvents/EventItemList.jsx
- src/components/CommunityEvents/EventItemListElement.jsx
- src/components/CommunityEvents/ModifyCommunityEvent.jsx
- src/components/CommunityEvents/events.json
related to issue #564
https://github.com/thecyberworld/TheCyberHUB/assets/76536506/f374867c-464e-44b6-b3e5-e1bffc4c7c10
Next I will work on backend and redux 
---
> feat: manage community events | handle edit option

- src/components/AIChat/AIChat.jsx
- src/components/AIChat/Prompts/PromptCard.jsx
- src/components/AIChat/Prompts/Prompts.jsx
- src/components/AIChat/Prompts/prompts.json
- src/components/AIChat/prompts.json
- src/components/CheatSheets/HackBook/HackBook.jsx
- src/components/Common/MarkdownEditor/useImageUploadEvents.jsx
- src/components/Courses/NewCourses/Course.jsx
- src/components/Courses/NewCourses/NewCourses.jsx
- src/components/Dashboard/FormData/InternshipResponse.jsx
- src/components/Dashboard/Profile/ConnectionsAndFollows/Connections/Connection.jsx
4 Prompts are added  in the ai chat section and the code is optimized. 
---
> feat: ai prompts are added

- src/components/CommunityEvents/ModifyCommunityEvent.jsx
why: so admins could edit date of an event
how: get in milliseconds and convert to Date stracture
https://github.com/thecyberworld/TheCyberHUB/assets/76536506/240d075b-052e-4d2c-ba65-f6ad6b9921d7
---
> fix: make editing date of event to work

- src/components/Explore/FeedsExplore.jsx
- src/components/Feeds/FeedPage/FeedComments/FeedComments.jsx
- src/components/Feeds/FeedPage/FeedPage.jsx
> fix: add check for bookmarks data

- src/components/CommunityEvents/CommunityEvents.jsx
- src/components/CommunityEvents/EventItemList.jsx
- src/components/CommunityEvents/ModifyCommunityEvent.jsx
- src/components/Opportunities/DisplayCommunityEvents/DisplayCommunityEvents.jsx
- src/features/events/eventsService.js
- src/features/events/eventsSlice.js
- src/features/userDetail/userDetailSlice.js
https://github.com/thecyberworld/TheCyberHUB/assets/76536506/e8e2648c-5efc-4286-b121-a7232bef1599
---
> feat: events | event participants, connect to backend and some more fixes 

- src/components/Dashboard/Profile/ConnectionsAndFollows/ConnectionsAndFollows.jsx
why: so users could follow and unfollow each other how: after the user is follows we need to fetch the followed user data and not our data
fixes issue #598
and not our data
https://github.com/thecyberworld/TheCyberHUB/assets/76536506/3eacf137-e42a-4b22-a9fe-8fda22957fda
---
> fix: follow-and-unfollow-functionality

- src/components/Tools/PassGen/PassGen.jsx
fixes #634
The generated password  reflect the length specified by the user in the 'Length' option, irrespective of the selection or deselection of 'Symbols'.
---
> fix: pass generator

- src/components/Feeds/FeedPosts/PostActionsAndStats.jsx
- src/components/Feeds/FeedTags/FeedTags.jsx
- src/components/Feeds/FeedTags/FeedTagsElements.jsx
- src/components/Feeds/Feeds.jsx
related to issue #626
I have made the following enhancements to address the issues in the Feeds section:
- Clicking on the comment icon in each post now opens the comment section of that specific post.
- Implemented functionality for trending tags in the sidebar.
- Clicking on a tag filters the posts based on the chosen tag.
- Clicking on another tag removes the previous tag and filters the posts based on the new one.
- If the same tag is clicked again, it is removed from the filter.
I attempted to implement a function to filter multiple tags, but encountered an issue when tag names contain spaces. This functionality is currently not supported due to this limitation.
---
Feel free to check out other cool …
> feat: Feeds Section | Enable Click Functionality for Trending Tags and Comments in Posts

- src/components/Homepage/Registration/Form.jsx
- src/pages/Register.jsx
Closes #629 
I was asked to make a notification checkbox in the registration page. I've made the said checkbox, however it lacks functionality. I've commented out the onchange function to be executed on ticking the checkbox and would like to correspond with the collaborator before enabling it. 
Before
After
Again it lacks functionality and I would be interested in working on that too. 
[x] - I've made a notification checkbox
[ ] - Its functional
I'd be interested in learning how to make it functional.
> feat: registration | Add a notification checkbox without functionality

- src/components/Explore/FeedsExplore.jsx
- src/components/Feeds/FeedPage/FeedComments/AddFeedComment.jsx
- src/components/Feeds/FeedPage/FeedComments/FeedComments.jsx
- src/components/Feeds/FeedPage/FeedComments/ReplyCard.jsx
- src/features/feeds/feedLikes/feedLikesServices.js
- src/features/feeds/feedLikes/feedLikesSlice.js
none
https://github.com/thecyberworld/TheCyberHUB/assets/76536506/95fbb94b-b4f7-4834-9ed8-f8c55cb3ac61
https://github.com/thecyberworld/TheCyberHUB/assets/76536506/9fd05382-bbb1-4c3e-bae1-5fe96576f919
I saw a few bugs so I fixed them without opening an issue.
---
> fix: explore | Check if user is not logged in and act accordingly

- src/components/Tools/Dorking/Dorking.jsx
- src/components/Tools/Tools.jsx
- src/components/Tools/ToolsRoute.jsx
> feat: tools | dorking

- src/components/Dashboard/OldDashbaord/GoalSetter/GoalForm.jsx
Modified the styling of the input field in the GoalForm component.
Changed the text color to ensure it's visible when entering a goal. 
---
> style: goals | goal-input-improvement

- src/components/Explore/Explore.jsx
closes #604 
four new arrays (allusers, following, follower, connection) are created having userId of users and only that data is shown whose userId are present in the new created array.
In this way filter option is implemented.
I am facing a small issue.
when the page reloads then it is not showing any data , but when I click on any filter buttons after that it works fine. It looks like It is trying to access the data before it is even loaded.
---
Join the Thecyberworld GitHub Organisation by raising an [issue](https://github.com/thecyberworld/Support/issues/new?assignees=&labels=invite+me+to+the+organisation&tem …
> feat: Explore | Show Only Users That Connected With Current User

- src/components/Blogs/BlogFilter.jsx
- src/components/Blogs/Blogs.jsx
- src/components/Blogs/BlogsElements.jsx
Closes #600 
A new select option is created for selecting "all" blogs or "following" blogs.
The select option is added in the right side as shown in screenshot.
---
> feat: blogs | blog filter option is added

- src/components/Common/SearchInputBox/SearchInputBox.jsx
- src/components/Common/SearchInputBox/SearchInputBoxElements.jsx
- src/components/Feeds/FeedPosts/FeedPosts.jsx
- src/components/Feeds/Feeds.jsx
#626
This pull request addresses the issue of enhancing tag filtering functionality in the Feeds section to allow users to filter posts by multiple tags simultaneously. 
https://github.com/thecyberworld/TheCyberHUB/assets/147496504/c6f2eb17-5f9e-43bc-b7ad-e9ce8dc5b415
In the video, there are more tags available for experimentation compared to the tags present in the development environment. Please note that I've added these additional tags just  for testing purposes but did not include them in the final commit for this pull request. 
--- …
> feat: Feeds | Implement Multiple Tag Filtering Functionality

- README.md
none
the icon of github :octocat: 
---
> docs: add link in readme to the development website

- src/components/AdminDashboard/ManageCommunityEvents/ManageCommunityEvents.jsx
- src/components/AdminDashboard/ManageCommunityEvents/ManageCommunityEventsElements.jsx
- src/components/CommunityEvents/CommunityEvents.jsx
- src/components/CommunityEvents/ModifyCommunityEvent.jsx
- src/components/CommunityEvents/ModifyCommunityEventElement.jsx
- src/components/CommunityEvents/ModifyElements.jsx
- src/components/CommunityEvents/ModifyTimeLine.jsx
- src/components/CommunityEvents/TimeLineListItemDisplay.jsx
- src/components/CommunityEvents/TimePickerDisplay.jsx
https://github.com/thecyberworld/TheCyberHUB/assets/76536506/eea69114-f4f3-42a7-b689-ef5688df8b82
I did only the display without functionality - this I will do next.
---
> feat: events | add events timeline display

- src/components/CaptureTheFlag/CTF.jsx
- src/components/Chat/Sidebar/Sidebar.jsx
- src/components/Common/SearchInputBox/SearchInputBox.jsx
- src/components/Common/SearchInputBox/SearchInputBoxElements.jsx
- src/components/Dashboard/Notetaker/NoteSidebar.jsx
- src/components/Explore/Explore.jsx
closes #655
- Adjusted the positioning of the cancel icon to prevent it from expanding the search box
- Ensured the cancel icon functions properly in all components ( CTF.jsx  Sidebar.jsx  NoteSidebar.jsx Explore.jsx ) 
---
> fix: Search Component Layout and Functionality

- src/components/Feeds/FeedPosts/FeedPosts.jsx
- src/components/Feeds/Feeds.jsx
- src/components/Feeds/FeedsElements.jsx
closes #601 
added filter button group on top of search box
---
> feat: Feeds | Add Filters Of Users

- src/components/Feeds/FeedPosts/PostActionsAndStats.jsx
- src/components/Header/UserOptions/UserOptions.jsx
- src/components/OldEvents/EventsData/HacktoberfestEventData.jsx
> fix:minor-issues

- src/components/Common/GeneralDashboardSidebar/GeneralDashboardSidebar.jsx
- src/components/Dashboard/Analytics/Analytics.jsx
- src/components/Dashboard/DashbaordSidebar/DashboardSidebar.jsx
- src/components/Header/Navbar/Navbar.jsx
- src/components/Resources/Methodology/MethodologyElement.jsx
- src/components/Resources/Methodology/MethodologyMain.jsx
- src/components/WebSecurity/Common/HintElements.jsx
- src/components/WebSecurity/Common/LabsRoom/LabsRoom.jsx
- src/components/WebSecurity/Common/LabsRoom/LabsRoomElement.jsx
- src/components/WebSecurity/Common/SubmissionBox.jsx
- src/components/WebSecurity/Sidebar.jsx
- src/components/WebSecurity/WebSecurityRoutes.jsx
- src/components/WebSecurity/WebSecurityTopics/Topics.jsx
> feat: web security

- src/components/Blogs/Blogs.jsx
- src/components/Common/SearchInputBox/SearchInputBox.jsx
- src/components/Dashboard/Profile/ConnectionsAndFollows/Follow/Follow.jsx
- src/components/Explore/Explore.jsx
- src/components/Feeds/FeedTags/FeedTagsElements.jsx
- src/components/Feeds/FeedsElements.jsx
- src/components/Feeds/PostForm/AddFeed.jsx
- src/components/Feeds/SocialSidebar/Sidebar.jsx
- src/components/Homepage/Info/Data.jsx
- src/components/Homepage/SpecialSponsors/SpecialSponsors.jsx
- src/components/Learn/Roadmaps/Roadmaps.jsx
- src/components/Opportunities/Volunteer/Volunteer.jsx
- src/components/Other/CyberGames/Leaderboard/Leaderboard.jsx
- src/components/Other/Security/RulesOfEngagement.jsx
- src/components/Other/Security/Security.jsx
- src/components/Resources/Jobs/JobDetailsPage.jsx
- src/components/Resources/Quiz/Categories/QuizPage.jsx
- src/components/Resources/Quiz/CreateQuiz/Main.jsx
- src/components/Tools/BinaryExploits/DataPages.jsx
- src/components/WebSecurity/Common/LabsRoom/LabsRoom.jsx
- src/components/WebSecurity/Common/SubmissionBox.jsx
- src/components/WebSecurity/SubHeader.jsx
- src/components/WebSecurity/WebSecurityTopics/SubTopic.jsx
- src/components/WebSecurity/WebSecurityTopics/Topic.jsx
> fix: common sidebar

- src/components/Common/InputEditor/InputEditor.jsx
- src/components/Common/InputEditor/InputEditorElements.jsx
- src/components/CommunityEvents/ModifyElements.jsx
- src/components/CommunityEvents/ModifyTimeLine.jsx
- src/components/CommunityEvents/TimeLineListItemDisplay.jsx
https://github.com/thecyberworld/TheCyberHUB/assets/76536506/6af9ce4c-82ee-469a-a7b1-b70c0782448a
---
> feat: events | timeline functionality

- src/App.jsx
- src/components/Header/Dropdowns/Dropdown.jsx
- src/components/Other/Victimhelp/Victimhelp.jsx
- src/components/Other/Victimhelp/VictimhelpElements.jsx
- src/components/index.js
> added new victim help page

- src/components/Resources/Methodology/MethodologyMain.jsx
fixed the dropdown issue and icon issue in methodology. 
---
> fix: fixed the dropdown issue in methodology.

- src/components/Common/Tags/filterByTags.js
- src/components/Explore/FeedsExplore.jsx
- src/components/Feeds/SocialSidebar/Sidebar.jsx
closes #662
Created the Tags directory in the common folder to accommodate tag-related functionality.
Moved filterByTags functionality to common/Tags/filterByTags.jsx
The Tags directory serves as a potential hub for future tag-related functions. For instance, I'm considering implementing a feature to identify top trending tags based on usage.)
---
Join the Thecyberworld GitHub Organisation by raising an [issue](https://github.com/thecyberworld/Support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization) (you will be sent an …
> Relocate-Tag-Filtering-Functionality

- src/components/Tools/BinaryExploits/BinaryExploits.jsx
- src/components/Tools/BinaryExploits/BinaryExploitsElements.jsx
- src/components/Tools/Tools.jsx
> fix: tools | binary exploit | designs

- src/components/Common/MultipleSelect/MultipleSelect.jsx
- src/components/Common/MultipleSelect/MultipleSelectElements.jsx
- src/components/Common/MultipleSelect/index.js
- src/components/CommunityEvents/CommunityEvents.jsx
- src/components/CommunityEvents/ModifyCommunityEvent.jsx
- src/components/CommunityEvents/ModifyElements.jsx
- src/components/CommunityEvents/ModifyTimeLine.jsx
- src/components/CommunityEvents/TimeLineListItemDisplay.jsx
- src/components/CommunityEvents/TimePickerDisplay.jsx
- src/utils/dateTimeRelatedFunctions.js
https://github.com/thecyberworld/TheCyberHUB/assets/76536506/7458d418-fb0f-417e-991b-63ac7b1078f2
- we can refactor all the places in the app to use this MultipleSelect common component 
- in next pr, I will use this in timeline , I didn't push yet because I have some bugs haha, preview:
---
> feat: events timeline backend connect

- src/components/Dashboard/Analytics/Analytics.jsx
- src/components/Feeds/FeedPosts/PostActionsAndStats.jsx
blogs and feeds data added in analytics.
feed and blogs data are used and the data which are currently unavailable are replaced by a dummyData (999).
---
> feat: blogs and feeds data added in analytics.

- src/App.jsx
- src/components/Common/DurationDisplay/DurationDisplay.jsx
- src/components/Common/DurationDisplay/DurationDisplayElements.jsx
- src/components/Common/DurationDisplay/index.js
- src/components/Common/TimePickerDisplay/TimePickerDisplay.jsx
- src/components/CommunityEvents/CommunityEvents.jsx
- src/components/CommunityEvents/CommunityEventsElement.jsx
- src/components/CommunityEvents/EventItemList.jsx
- src/components/CommunityEvents/ModifyElements.jsx
- src/components/CommunityEvents/ModifyTimeline.jsx
- src/components/CommunityEvents/ParticipantsDisplayElement.jsx
- src/components/CommunityEvents/TimelineListItemDisplay.jsx
- src/components/Dashboard/Profile/EditPublicProfile/EditUserLinks.jsx
- src/components/Dashboard/Profile/UserLinks/UserInfo.jsx
- src/components/Dashboard/Profile/UserLinks/UserLinks.jsx
- src/components/Dashboard/Profile/UserLinks/UserLinksElements.jsx
- src/components/Opportunities/DisplayCommunityEvents/DisplayEventDetails.jsx
- src/components/Opportunities/DisplayCommunityEvents/DisplayEventDetailsElement.jsx
- src/components/Opportunities/DisplayCommunityEvents/DisplayTimelineElements.jsx
- src/components/Opportunities/DisplayCommunityEvents/DisplayTimelineItem.jsx
- src/components/Opportunities/DisplayCommunityEvents/DisplayTimelineList.jsx
- src/components/Opportunities/DisplayCommunityEvents/index.js
- src/utils/dateTimeRelatedFunctions.js
https://github.com/thecyberworld/TheCyberHUB/assets/76536506/f1bd61c5-a343-4221-b0cf-2bab9b7c7733
- I have many tasks left related to events, I will continue working on them.
---
> feat: event details display

- package-lock.json
- package.json
- src/components/CommunityEvents/CommunityEvents.jsx
- src/components/CommunityEvents/EventItemList.jsx
- src/components/CommunityEvents/EventItemListElement.jsx
- src/components/CommunityEvents/ParticipantsDisplay.jsx
- src/components/Feeds/FeedPosts/FeedPostsElements.jsx
- src/components/Opportunities/DisplayCommunityEvents/DisplayEventDetails.jsx
- src/components/Opportunities/DisplayCommunityEvents/DisplayEventDetailsElement.jsx
- src/components/Opportunities/DisplayCommunityEvents/DisplayTimelineElements.jsx
- src/components/Opportunities/DisplayCommunityEvents/DisplayTimelineItem.jsx
https://github.com/thecyberworld/TheCyberHUB/assets/76536506/2f8564cf-1410-45a2-ad0d-7231fde35abe
---
> feat: event details display , more changes

- src/App.jsx
- src/components/CaptureTheFlag/CTFLeaderboard/CTFLeaderboardElements.jsx
- src/components/CaptureTheFlag/CtFPage/MainPage.jsx
- src/components/CaptureTheFlag/CtFPage/MainPageElement.jsx
- src/components/CaptureTheFlag/CtFPage/QuestionAnswer.jsx
- src/components/CaptureTheFlag/CtFPage/QuestionAnswerComponent.jsx
- src/components/CaptureTheFlag/CtFPage/QuestionAnswerComponentElement.jsx
> Ctf Ui update

- src/app/store.js
- src/features/blogs/blogLikes/blogLikesServices.js
- src/features/blogs/blogLikes/blogLikesSlice.js
Like feature in blogs are implemented.
Blogs like service and blogs like slice are created and blogs like is added to the redux store.
---
> feat: blogs like feature implemented

- src/components/WebSecurity/CrackMe/CrackMeData.jsx
> feat: websecurity | crackme new data

- src/components/Homepage/ContactForm/ContactForm.jsx
#695
now should display an error message indicating the email is invalid.
---
> fix: contact form | email-validation

- src/components/Explore/Explore.jsx
Closes #690
This pull request fixes an issue in the Explore section. Previously, selecting 'all' filter with no items available displayed 'Not Found' message four times. 
Changes:
1. Moved the empty list check to the Explore component. It now checks if all item lists are empty and displays a single 'Not Found' message if true.
This change provides a cleaner interface when no items are available.
---
Join the Thecyberworld GitHub Organisation by raising an [issue](https://github.com/thecyberworld/Support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the …
> Explore | Combine all the empty data fields

- src/components/Homepage/ContactForm/ContactForm.jsx
Closes #696
- [] I have updated the documentation accordingly.
---
> feat: contact form | Sumbitted succefully mechanism

- src/components/Feeds/FeedPosts/FeedPostsElements.jsx
- src/components/Homepage/ContactForm/ContactForm.jsx
> Fix: feeds | fead post design in explore section

- src/components/Homepage/ContactForm/ContactFormElements.jsx
Closes #566 
adjust the styling of the contact form
---
> style: contact form | update styles

- src/components/Feeds/FeedPosts/FeedPost.jsx
- src/components/Feeds/FeedPosts/FeedPostsElements.jsx
> fix-username and date overlapping

- src/components/Homepage/ContactForm/ContactFormElements.jsx
> fixed the form styles to be adaptive for mobile

- src/components/Dashboard/Profile/UserPoints/UserPoints.jsx
- src/components/Dashboard/Profile/UserPoints/UserPointsElements.jsx
- src/components/Header/ExpElemenets.jsx
> style: public profile | Icon bug fixed

- src/components/CaptureTheFlag/CTFRoute.jsx
- src/components/CaptureTheFlag/CtFPage/MainPage.jsx
- src/components/CaptureTheFlag/CtFPage/MainPageElement.jsx
- src/components/CaptureTheFlag/CtFPage/QuestionAnswer.jsx
- src/components/CaptureTheFlag/CtFPage/QuestionAnswerComponent.jsx
- src/components/CaptureTheFlag/CtFPage/Submission.jsx
- src/components/CaptureTheFlag/SingleCTF/SingleCTF.jsx
> feat: Ctf page | make it dynamic page

- src/components/Header/Dropdowns/DropdownElements.jsx
- src/components/Header/Navbar/Navbar.jsx
- src/components/Header/Navbar/NavbarElements.jsx
- src/components/Header/Sidebar/Sidebar.jsx
- src/components/Header/Sidebar/SidebarElements.jsx
See video!
Old:-
https://github.com/thecyberworld/TheCyberHUB/assets/118581404/0353ea16-acc8-4bbf-b69e-cdb0c8acc18c
Fixed:-
https://github.com/thecyberworld/TheCyberHUB/assets/118581404/ec557eb2-c3e8-4bdb-acaf-542964903133
Feel free to tell me any changes you want!
---
> feat: Mobile Layout, Dispaly SubMenu

- src/components/CommunityEvents/CommunityEvents.jsx
> fix: build error

- src/components/Dashboard/Analytics/Analytics.jsx
- src/components/Dashboard/Analytics/AnalyticsBarChart.jsx
- src/components/Dashboard/Analytics/AnalyticsDoughnutChart.jsx
- src/components/Dashboard/Analytics/AnalyticsMainBarChart.jsx
- src/components/Dashboard/Analytics/AnalyticsStackedBar.jsx
- src/components/Dashboard/Analytics/useAnalyticsChartCustomHook.jsx
> fix-build-errors,remove 'use client'

- src/components/Dashboard/Analytics/AnalyticsBarChart.jsx
- src/components/Dashboard/Analytics/AnalyticsDoughnutChart.jsx
- src/components/Dashboard/Analytics/AnalyticsMainBarChart.jsx
- src/components/Dashboard/Analytics/AnalyticsStackedBar.jsx
> change the default exports

- package-lock.json
- src/components/Dashboard/Analytics/Analytics.jsx
- src/components/Dashboard/Analytics/AnalyticsBarChart.jsx
- src/components/Dashboard/Analytics/AnalyticsDoughnutChart.jsx
- src/components/Dashboard/Analytics/AnalyticsMainBarChart.jsx
- src/components/Dashboard/Analytics/AnalyticsPageBottomSectionMainContent.jsx
- src/components/Dashboard/Analytics/AnalyticsPageTopSectionMainContent.jsx
- src/components/Dashboard/Analytics/AnalyticsStackedBar.jsx
- src/components/Dashboard/Analytics/AnalyticsTopInnerCards.jsx
- src/components/Dashboard/Analytics/useAnalyticsChartCustomHook.jsx
- src/components/Dashboard/DashboardRoute.jsx
> Fixing errors

- package-lock.json
- package.json
- src/components/Dashboard/Analytics/AnalyticsBarChart.jsx
- src/components/Dashboard/Analytics/AnalyticsDoughnutChart.jsx
- src/components/Dashboard/Analytics/AnalyticsMainBarChart.jsx
- src/components/Dashboard/Analytics/AnalyticsStackedBar.jsx
- src/components/Dashboard/Analytics/AnalyticsUtils.js
> fix: remove react-horizontal-stacked-bar-chart it did a bug with vite

- src/components/Explore/Explore.jsx
Closes #689 
created a allUsers variable which contains the user_id of all users registered, when any user clicks on previously selected Filter then the filter gets deselected and posts, blogs , etc of all users become visible.
---
> feat: Explore | Option for Non Selected added.

- .github/ISSUE_TEMPLATE/responsive_web.yml
why: to open general issue for users to create new responsive_web related issues
none
---
> docs: add responsive_web template

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/doc_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/ISSUE_TEMPLATE/other.yml
- .github/ISSUE_TEMPLATE/responsive_web.yml
- .github/pull_request_template.md
> docs: Change broken coc url

- README.md
Update Twitter Logo in README #751
https://github.com/thecyberworld/TheCyberHUB/issues/751
The Twitter logo in the README file needs to be updated to the latest branding. Currently, the README displays the old Twitter logo, and it should be replaced with the new "x" logo to reflect the most recent changes.
---
> docs: change the twitter logo to X logo

- src/components/Common/GeneralDashboardSidebar/GeneralDashboardSidebar.jsx
related to issue https://github.com/thecyberworld/TheCyberHUB/issues/759
when clicking on the profile image it will redirect the user to his profile
---
> feat: dashboard | add link to the user profile image

- src/components/Dashboard/OldDashbaord/GoalSetter/GoalForm.jsx
Closed #756, now you can`t submit the button if the text is empty :
> fix: goals | prevent form submit if text is empty

- src/components/Feeds/FeedPage/FeedComments/ReplyCard.jsx
- src/components/Feeds/FeedPage/FeedPagePost.jsx
- src/components/Feeds/FeedPosts/FeedPost.jsx
> fix: feeds | user is undefined when the user is not registered

- README.md
no related issue
in the installation guide it is mentioned to copy the content of .env.example into the .env file.
However the correct file name  for the first is example.env.
---
> fixed example.env file name

- src/components/Chat/ChatBox/ChatBox.jsx
> fix: move the api check after hooks

- src/components/WebSecurity/WebSecurityTopics/SubTopic.jsx
- src/components/WebSecurity/WebSecurityTopics/Topic.jsx
closes https://github.com/thecyberworld/TheCyberHUB/issues/715
add a scrolling motion when clicking on the subtopic button in the side bar 
https://github.com/thecyberworld/TheCyberHUB/assets/157605627/159b126f-d4f2-4b18-9daa-7264f1980321
---
You can also join our …
> scrolling function for topics

- src/components/Resources/Quiz/Categories/QuizPage.jsx
> modify button position

- src/components/Resources/InterviewQuestions/InterviewQuestions.jsx
- src/components/Resources/InterviewQuestions/InterviewQuestionsData.jsx
- src/components/Resources/InterviewQuestions/InterviewQuestionsElements.jsx
closes #775 
Now , selected questions are highlighed with orange color 
-   [x] My change requires changes to the documentation.
-   [x] I have updated the documentation accordingly.
---
Join the Thecyberworld GitHub …
> fixed selected question indicator

- src/components/Chat/ChatBox/UserList.jsx
#786 
Reclick on chat will close the Chat box
---
Join the Thecyberworld GitHub Organisation by raising …
> feat: chatbox | user close functionality

- README.md
> docs: readme | Docs update readme

- src/components/Chat/ChatBox/ChatBox.jsx
> Search Function in chatbox

- src/components/WebSecurity/WebSecurityTopics/topicsData.jsx
> feat: websecurity topics data

- src/components/Common/SearchInputBox/SearchInputBoxElements.jsx
- src/pages/Login.jsx
Added Change Password type Button (Toggle) in Login.jsx
-   [X] By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/thecyberworld/TheCyberHUB/blob/dev/CODE_OF_CONDUCT.md) 🖖
-   [X] My code follows the code style of this project.
-   [X] I have updated the documentation accordingly.
-   [X] All new and existing tests passed.
-   [X] This PR does not contain plagiarized content.
-   [X] The title of my pull request is a short description of the requested changes.
---
> Feature/Add Show Password Option #779

- src/components/Blogs/ReactBarr/ReactBar.jsx
- src/components/Blogs/ViewBlog/ViewBlog.jsx
> add floating like comment and share button in blog

- src/components/Tools/EncoderDecoder.jsx/DecoderCode.jsx
Hey, in my last pr, I seem to have made a mistake:
if you refer to #819  and #818 I think that I never pushed the decoder file changes (what you saw in the pr video was the changes that included all the files) 
Adding missing changes in this pr
> Using code container in decode fields as well

- src/components/Common/MarkdownEditor/MarkdownEditor.css
Closes #812 
- I went ahead and resolved the bug that was causing the Cursor to appear over the text and out of place.
- This was caused by the text area not recognizing the font change of size for the code tags.
- I went ahead and resolved the odd look of the tags as well with the padding.
- Resolution was to make the tags same font-size as the textarea, remove padding and remove a margin that was on the closing tag.
Let me know if you'd prefer a smaller font for the tags and I will try to resolve a different solution. The textarea being position: absolute; is what causes the confusion towards its relative.
-   [x] My code …
> Fixed styling issue causing cursor position error in Notes section, Resolves #812

- src/components/Header/Dropdowns/DropdownElements.jsx
> style: fix bg color of navbar which was accidentally removed

- src/components/Learn/Roadmaps/RoadmapsData.jsx
- src/components/WebSecurity/CodeReviews/CodeReviewData.jsx
- src/components/WebSecurity/Common/Labs/LabsData.jsx
- src/components/WebSecurity/WebSecurityTopics/topicsData.jsx
> some minor changes & new code review data added

- src/components/Blogs/ManageBlogs/CreateBlogV2/CreateBlogV2.jsx
- src/components/Common/ImageUpload/ImageElements.jsx
- src/components/Common/ImageUpload/ImageInput.jsx
- src/components/Common/ImageUpload/ImagePreview.jsx
- src/components/Common/ImageUpload/index.js
- src/components/Common/ImageUpload/useUploadImages.jsx
- src/components/Feeds/FeedPosts/FeedPost.jsx
- src/components/Feeds/FeedPosts/FeedPosts.jsx
- src/components/Feeds/PostForm/ModifyFeed.jsx
none
https://github.com/thecyberworld/TheCyberHUB/assets/76536506/087e4419-f204-490c-b3eb-3a7526177731
https://github.com/thecyberworld/TheCyberHUB/assets/76536506/8a021a19-16b3-4be5-983c-4a302d52094b
Need to do:
-   [X] By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/thecyberworld/TheCyberHUB/blob/dev/CODE_OF_CONDUCT.md) 🖖
-   [X] My code follows the code style of this project.
-   [X] All new and existing tests passed.
-   [X] This PR does not contain plagiarized content.
-   [X] The title of my pull request is a short description of the requested changes.
---
You can also join our [Discord](https://discord.gg/QHBPq6xP5p) …
> refactor: image upload hook | create + use in modify feed and create blog

- src/features/auth/authService.js
- src/features/auth/authSlice.js
- src/pages/Login.jsx
- src/pages/Register.jsx
> feat: 2fa login

- src/components/Blogs/BlogCard/BlogCardElements.jsx
- src/components/Blogs/BlogSidebar/LeftBlogSidebarElements.jsx
- src/components/Blogs/BlogsElements.jsx
- src/components/Blogs/ManageBlogs/CreateBlog/CreateBlog.jsx
- src/components/Blogs/ManageBlogs/CreateBlog/CreateBlogElements.jsx
- src/components/Blogs/ManageBlogs/CreateBlogV2/BlogPostFormV2.jsx
- src/components/Blogs/ManageBlogs/CreateBlogV2/CreateBlogV2.jsx
- src/components/Blogs/ManageBlogs/CreateBlogV2/CreateBlogV2Elements.jsx
- src/components/Blogs/ManageBlogs/EditBlog/EditBlog.jsx
- src/components/Blogs/ViewBlog/ViewBlogElements.jsx
- src/components/Common/ImageUpload/ImageElements.jsx
- src/components/Common/ImageUpload/ImageInput.jsx
- src/components/Common/ImageUpload/ImagePreview.jsx
- src/components/Common/ImageUpload/useUploadImages.jsx
- src/components/Feeds/FeedPosts/FeedPostsElements.jsx
- src/components/Feeds/FeedTags/FeedTagsElements.jsx
- src/components/Feeds/PostForm/AddPostElements.jsx
- src/components/Feeds/PostForm/AddPostTags/AddPostTagsElements.jsx
- src/components/Feeds/PostForm/ModifyFeed.jsx
- src/features/imageUploadService.js
Resolve change to merge into dev instead of dev-01 with cherry-pick of pr #848 
---
Join the …
> fix: cherry pick of pr 848

- src/components/AIChat/AIChatElements.jsx
- src/components/AIChat/RecentChatsElements.jsx
Closes https://github.com/thecyberworld/TheCyberHUB/issues/805
---
Join the Thecyberworld GitHub …
> AIChat responsive fix - requested changes

- src/components/AIChat/AIChat.jsx
- src/components/AIChat/AIChatElements.jsx
- src/components/AIChat/Prompts/Prompts.jsx
- src/components/AIChat/RecentChatsElements.jsx
Closes #805 
- added overflow on chat content
- recent chat box moved to absolute positioning under 800px to avoid overcrowding on mobile devices
- overlapping grid styles in Prompts component removed
[337881101-7dbfa97c-07a9-4375-956f-68fceb7f6f97.webm](https://github.com/thecyberworld/TheCyberHUB/assets/76536506/c70f0124-2d65-47fb-8691-5d155448bc31)
done by @SinanovicAhmed 
It is a cherry pick duo to changed dev branch …
> fix: AIChat responsive fix - cherry pick of pr 844

- src/components/Blogs/ManageBlogs/CreateBlogV2/CreateBlogV2.jsx
- src/components/Common/ImageUpload/CompressImage.jsx
- src/components/Common/ImageUpload/ImageInput.jsx
- src/components/Common/ImageUpload/ImagePreview.jsx
- src/components/Common/ImageUpload/useUploadImages.jsx
- src/components/Feeds/PostForm/ModifyFeed.jsx
- src/features/feeds/feedsService.js
- src/features/feeds/feedsSlice.js
- related to uploading images , and feeds
https://github.com/thecyberworld/TheCyberHUB/assets/76536506/75f0ad5f-8ffe-4d05-a731-386549e86ff8
https://github.com/thecyberworld/TheCyberHUB/assets/76536506/700d4b7f-ad33-46b5-8311-8f93c9e602e1
---
You can also join our …
> Fix: upload images+feeds

- src/components/AIChat/AIChat.jsx
- src/components/AIChat/AIChatElements.jsx
- src/components/AIChat/RecentChats.jsx
- src/components/AIChat/RecentChatsElements.jsx
Fixed responsiveness of AIChat, added button to go back and fixed misaligned button with bottom border
https://github.com/thecyberworld/TheCyberHUB/assets/131366333/28cb47c5-f578-48a2-aa1d-73fd1f7a90bb
-   [X] By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/thecyberworld/TheCyberHUB/blob/dev/CODE_OF_CONDUCT.md) 🖖
-   [X] My code follows the code style of this project.
-   [X] All new and existing tests passed.
-   [X] This PR does not contain plagiarized content.
-   [X] The title of my pull request is a short description of the requested changes.
---
Feel …
> Ai chat responsive

- src/components/Blogs/ManageBlogs/CreateBlogV2/CreateBlogV2.jsx
Closes #877 
- Changing the current implementation of `navigate to "/blogs"` on successful creation of article to `navigate to "/articles`
https://github.com/thecyberworld/TheCyberHUB/assets/36098162/01192bad-4950-4c7f-9e38-2cc68169e963
---
You can also join our …
> Redirect to articles page after creating new articale #877

- src/components/Blogs/ManageBlogs/CreateBlogV2/CreateBlogV2.jsx
Closes #878 
- Updating the category from "Blog" to "Article" in the create article form
https://github.com/thecyberworld/TheCyberHUB/assets/36098162/98369eb2-63bb-49fc-a865-5a5fd05ce965
---
Feel free to check …
> Fix Blog validation failed: category: "Blog" is not a valid enum value for path "category" #878

- src/components/Tools/GoogleDork/GoogleDorkMain.jsx
- src/components/Tools/Tools.jsx
- src/components/Tools/ToolsRoute.jsx
> Feature : tools/Google Dorks

- src/components/Resources/Hackliner/Hackliner.jsx
- src/components/Resources/ResourcesElements.jsx
- src/components/Tools/SubdomainFinder/SubdomainFinder.jsx
- src/components/WebSecurity/WebSecurityTopics/Topic.jsx
- src/components/WebSecurity/WebSecurityTopics/Topics.jsx
> fix: api call

- src/components/CaptureTheFlag/CTF.jsx
- src/components/WebSecurity/CodeReviews/RoomCard.jsx
- src/components/WebSecurity/Common/Labs/Labs.jsx
- src/components/WebSecurity/Sidebar.jsx
- src/components/WebSecurity/WebSecurityTopics/Topics.jsx
> fix: filters and performance

- src/components/Resources/Hackliner/Hackliner.jsx
- src/components/Resources/ResourcesElements.jsx
- src/components/Tools/SubdomainFinder/SubdomainFinder.jsx
- src/components/WebSecurity/WebSecurityTopics/Topic.jsx
- src/components/WebSecurity/WebSecurityTopics/Topics.jsx
> fix: api path

- src/components/Resources/Quiz/Categories/QuizPage.jsx
#907 
On skipping questions no score is added
Please accept this PR under Hacktoberfest
-   [x] My change requires changes to the documentation.
-   [x] I have updated the documentation accordingly.
---
Join the …
> score bug fixed

- src/components/CaptureTheFlag/CTF.jsx
> refactor & bug fixed

- src/components/Header/Dropdowns/Dropdown.jsx
- src/components/Header/Dropdowns/DropdownElements.jsx
- src/components/Header/Navbar/Navbar.jsx
- src/components/Header/Navbar/NavbarElements.jsx
- src/components/Header/Sidebar/Sidebar.jsx
- src/components/Header/Sidebar/SidebarElements.jsx
> feat: navbar | design

- src/components/Homepage/Footer/Footer.jsx
Closes #917 
- Changed community to contact us
> fix: corrected the footer link

- src/components/Homepage/ContactForm/ContactForm.jsx
- src/components/Homepage/ContactForm/ContactFormElements.jsx
- src/components/Homepage/Homepage.jsx
- src/components/Homepage/Info/Data.jsx
- src/components/Homepage/Info/Info.jsx
- src/components/Homepage/Info/InfoElements.jsx
- src/components/Homepage/Socials/Socials.jsx
- src/components/Homepage/Socials/SocialsElements.jsx
- src/components/Other/MixComponents/Buttons/ButtonElements.jsx
> feat: homepage, socials and contact | design
